### ISSUE TITLE
  error reading from connection

### ISSUE THREAD

**Issue by ajohi** [GreenleafLab/chromVAR#10]
I am getting following error when using compute_deviation. Anything I may be missing?
Error in value[[3L]](cond) : setting worker timeout:
  error reading from connection

**Comment by ajohi** [comment]
adding BiocParallel::register(BiocParallel::SerialParam()) before the call to copute_deviation fixed it.

**Comment by AliciaSchep** [comment]
Re-opening this issue as a reminder to add something to documentation or maybe a FAQ section about the possibility for this kind of error if BiocParallel not registered
