### ISSUE TITLE
How to asses group separation in tsne plots?

### ISSUE THREAD

**Issue by diazcastillo** [GreenleafLab/chromVAR#12]
Hi,

We successfully run chromVar on our data, and now we are wondering on how to asses the significance of the separation of tsne plot groups of samples. Our two groups of samples do not separate so well, but if we were to draw a vertical line at 0 in the tSNE dim 1 axis, the distribution of samples for each group with regard to this line is significantly different using a Chi square test. However, I am a bit skeptical on the appropriateness of performing a Chi square test to compare the distribution of samples from two groups at either side of a line that is drawn arbitrarily in these type of representations.

Does anyone have any suggestion on how to statistically asses the separation of two groups of samples on a tSNE plot?

Thanks a lot.

Carlos

**Comment by AliciaSchep** [comment]
I doubt drawing a line from tSNE is the best way to asses the separation of the groups in that case. I tend to think tSNE can be a useful visualization tool, but that it is best not to over-interpret the resulting quantities.

**Comment by diazcastillo** [comment]
That is my interpretation, but wanted to double check with someone with more experience on the subject. Thanks for the reply.
