### ISSUE TITLE
multicore typo

### ISSUE THREAD

**Issue by caleblareau** [GreenleafLab/chromVAR#13]
In the vignette-- https://greenleaflab.github.io/chromVAR/

`register(MultiCoreParam(8)) # Use 8 cores` should have a little 'c'
<-> 
`register(MulticoreParam(8)) # Use 8 cores`

I didn't check the rest of your examples / documentation to see if this pops up other places

**Comment by AliciaSchep** [comment]
Thanks for noticing this, fixed now.
