### ISSUE TITLE
computeDeviations bug

### ISSUE THREAD

**Issue by caleblareau** [GreenleafLab/chromVAR#14]
hey @AliciaSchep--

I had some code that was working for an older version of chromVAR (pre-camelCase days) that now is giving me this error:

```
Error in vapply(results, function(x) x[["matches"]], 0) : 
 values must be length 1,
but FUN(X[[227]]) result is length 0
Calls: computeDeviations ... computeDeviations -> .local -> compute_deviations_core -> vapply
Execution halted
```

It looks like all of my Z/Deviation scores are properly computed, but creating the summary stats (I think is new?) fails out I think here-- https://github.com/GreenleafLab/chromVAR/blob/master/R/compute_deviations.R#L395

I'm using pretty big data, so hard to give a MWE, but also not impossible if you can't reproduce it or see what's going on right away. I'm using the cisBP motif list from chromVARmotifs.

**Comment by AliciaSchep** [comment]
Hi @caleblareau ,Yeah summary stats are new, based on reviewer comment. Seems like issue might be with 227th motif?  Any thing strange with that one, i.e. are there any motif matches? If you just use that motif, does error occur also?

**Comment by caleblareau** [comment]
Yeah digging into it a bit deeper, this motif--
```
>  human_pwms_v1[227]
PWMatrixList of length 1
names(1): ENSG00000250542_LINE569_ENSG00000250542_I
```
Comes up with zero matches
```
> one <- human_pwms_v1[227]
> motif_ix <- matchMotifs(one, combined, genome = BSgenome.Hsapiens.UCSC.hg19)
> sum(motif_ix@assays$data@listData$motifMatches)
[1] 0
```

Which seems a bit surprising since I was using like 500k 500bp peaks, but whatever. Anyways, yeah my guess would be if you tweaked your `vapply` with an `ifelse` you'd probably fine.

**Comment by AliciaSchep** [comment]
This bug should now be fixed.  Problem was in code handling situation with no motifs.
