### ISSUE TITLE
Error installing chromVAR, GO.db not installed

### ISSUE THREAD

**Issue by timydaley** [GreenleafLab/chromVAR#17]
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘GO.db’
ERROR: lazy loading failed for package ‘chromVAR’

**Comment by AliciaSchep** [comment]
What was the installation mechanism here that lead to this error? i.e. was this result from calling install_github?

**Comment by timydaley** [comment]
Yes.  Do you have another way to install it?

**Comment by caleblareau** [comment]
If I recall correctly, `GO.db` is a nested dependency of one of the packages that `chromVAR` depends on. @timydaley does the following work?
```
source("https://bioconductor.org/biocLite.R")
biocLite("GO.db")
devtools::install_github("GreenleafLab/chromVAR")
```

**Comment by timydaley** [comment]
Yes.  But I wanted y'all to be aware of the issue.

**Comment by AliciaSchep** [comment]
You can also install packages from Github using biocLite, e.g. `BiocInstaller::biocLite("GreenleafLab/chromVAR")`.  This may do better at installing the BioC dependencies, but I'm not sure.  Anyways I don't think this is really chromVAR problem, except for the documentation & what recommendation for installation is.

**Comment by timydaley** [comment]
That's good to know.  I'll change my scripts to reflect this change.  Thank you.

**Comment by ttriche** [comment]
if there are BioC dependencies or imports declared for a package on GitHub,
biocLite("author/package") will indeed do a better job of chasing them down.

--t

**Comment by AliciaSchep** [comment]
Thanks @ttriche for confirmation (and @timydaley for bringing up the issue), I'll re-open this issue as a reminder to update docs to recommend biocLite installation instead of install_github.

**Comment by AliciaSchep** [comment]
readme updated to recommend biocLite

**Comment by Funshope** [comment]
Thanks alot! I have finally installed chromVAR on my computer.

**Comment by Funshope** [comment]
Is there a course organized or going to be organized on ATAC-Seq data analysis? My colleagues and I are really interested in attending.

**Comment by AliciaSchep** [comment]
@Funshope I would ask that question on the [ATAC-seq forum](https://sites.google.com/site/atacseqpublic/home?pli=1). I think various places have hosted related courses, but don't know specifically.
