### ISSUE TITLE
Error: Computing deviation for bulk ATAC seq data

### ISSUE THREAD

**Issue by parvathisudha** [GreenleafLab/chromVAR#21]
Hi,
I am trying to analyze ATAC seq data in chromVAR. The input files are peak file generated from MACS2 (using treatment and control) and treatment.bed file. In this case how do I calculate deviation? 
I computed background using "getBackgroundPeaks(object = counts_filtered)"
Then I was trying to compute the deviation using that background and it gives an error. 

dev <- computeDeviations(object = counts_filtered, annotations = motif_ix, background_peaks = bg)
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent

Can you please help me? Is there a different steps you follow when analyzing the bulk ATAC seq data?

**Comment by AliciaSchep** [comment]
What are the dimensions of counts_filtered, motif_ix, and bg?

**Comment by parvathisudha** [comment]
Hi,
The dimensions are,
> dim(counts_filtered)
[1] 60114     1
> dim(motif_ix)
[1] 60114  1346
> dim(bg)
[1] 60114    50

**Comment by AliciaSchep** [comment]
It does not make sense to run chromVAR on one sample as chromVAR identifies motifs or annotations associated with variability between samples.  If you only have one bulk sample, then motif enrichment methods (e.g. Homer) would be more appropriate. 

I'm guessing the one sample case is what is leading to error, although I haven't tested yet.  Ideally, the computeDeviations would check that there are more than one samples and if not return an error message that is more useful.

**Comment by parvathisudha** [comment]
Okay, Got you. 
I also tried with 2 samples (same treatment at two time points), and the variation was calculated. The input was merged peak file. 
Here, how do I interpret the variation. Is that between the samples?

**Comment by AliciaSchep** [comment]
Yes, the variability between the samples, e.g. higher value means samples more different from each other.  Expectation for randoms set of peaks would be 1.  Note that the bootstrap upper/lower bound won't make sense at all with just two samples (chromVAR was designed with single cell ATAC in mind, where you have 100s of cells).
