### ISSUE TITLE
the leading minor of order 2 is not positive definite

### ISSUE THREAD

**Issue by r3fang** [GreenleafLab/chromVAR#26]
get the following error from computeDeviations:
Error in chol.default(cov(norm_mat)) :
  the leading minor of order 2 is not positive definite

**Comment by r3fang** [comment]
BTW, i can get motif_ix (motif match) results and assay(motif_ix) seems to be a normal matrix

**Comment by r3fang** [comment]
Figured it out, there are NAs in "bias" calculated by addGCBias which was causing the problem.

**Comment by JBreunig** [comment]
How did you end up solving this?  I actually seeing this in the motif section of snapATAC.
 dev <- computeDeviations(object = rse, annotations = motif_mm);
Error in chol.default(cov(norm_mat)) : 
  the leading minor of order 2 is not positive definite

**Comment by r3fang** [comment]
if i remembered correctly, 

```R
rse <- addGCBias(rse, genome = BSgenome.Mmusculus.UCSC.mm10);
```

After this step, just replace the NA value in the matrix of `rse`. That's all i can remember. 

The other thing is to remove the cell/peak that coverage less than 10 coutns

**Comment by yanwu2014** [comment]
I think you actually have to replace the NA values in the rowData of the counts object, this worked for me:
```
row.data <- data.frame(rowData(rse))
row.data[is.na(row.data)] <- 0
rowData(rse) <- row.data
```

**Comment by JBreunig** [comment]
Thanks, I was just coming back to this problem!

**Comment by qiz218591** [comment]
I dont have any NA values in the dataset and still I am getting this error. 
May I get some insights and suggestions in this regard ?
Its too urgent and response is needed from your end that what can be done so far ??
As I have tried everything but coudnt able to figured it out?

**Comment by kabilanbio** [comment]
Thanks @yanwu2014, your solution has solved my error.
