### ISSUE TITLE
Without Error bar

### ISSUE THREAD

**Issue by dwb0211** [GreenleafLab/chromVAR#32]
Hi Alicia Schep,  Can I only plot the picture without Error bar in plotVariability in your excellent R package chromVAR?

**Comment by AliciaSchep** [comment]
Yes if you either run `computeVariability` with `bootstrap_error = FALSE` and use that as input or you modify the results of `computeVariability` to remove the columns bootstrap_lower_bound and bootstrap_upper_bound then `plotVariability` will not plot error bars. 

If you want further modification of the plot, I'd recommend taking a look at the [function's code](https://github.com/GreenleafLab/chromVAR/blob/master/R/plotting.R#L21) and adapting the ggplot call directly

**Comment by caleblareau** [comment]
@dwb0211 anecdotally, I typically do something like the following:

```
variabilityAll <- computeVariability(dev)

data.frame(variabilityAll) %>% arrange(desc(variability))-> motifVariability
motifVariability$rank <- 1:dim(variabilityAll)[1]
ggplot(motifVariability, aes(x = rank, y = variability)) + geom_point(size = 0.75) +
  labs(x = "Motif Rank", y = "Accessibility Variability")
```

**Comment by dwb0211** [comment]
Thank you guys so much @AliciaSchep @caleblareau
