### ISSUE TITLE
Sc Data Set

### ISSUE THREAD

**Issue by marianogabitto** [GreenleafLab/chromVAR#36]
Alicia,
    would it be possible to know if there is an already published dataset that I can use to explore chromVar?  I would like to get access to the raw data, so I can run alignments, filters, etc from scratch. Or at least after trimming and alignment. Bam Files would be great.

   I have downloaded the single cell profiles from GSE96772 (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE96772). I can get the sra files for each individual cell, I believe.

   But are these already trimmed and aligned? For example the description of the files said that we can get the bam files for the single cells already merged. How do I get this merged file?

Thanks a lot,

Mariano

P.S> Accession Description:
Supplementary_files_format_and_content: Bam files across single-cells representing identical biological conditions have been merged. Reads pertaining to individual cells can be identified by their unique RGID tag corresponding to each assayed well. Bed files represent 500 bp peak summits as described above.

**Comment by AliciaSchep** [comment]
@jdbuenrostro or @caleblareau can you help with this question?

**Comment by caleblareau** [comment]
hey @marianogabitto, if you download the SRA files from the GSE link that you posted above, these will be raw fastq files that can be processed as you described. If you want to run your own analysis from the alignment step, this is definitely the way to go.

**Comment by marianogabitto** [comment]
Thanks @caleblareau, just to clarify. From the SRA, I can get paired end fastq files. I want to know if these are the raw files or do they have any processing step already done?  Do I just align them or do I have to run an entire pipeline with read trimming, etc?

Thanks and sorry if I am not understanding correctly,

Mariano

**Comment by caleblareau** [comment]
These should be the raw files— you’ll need to do adapter trimming upstream of alignment.

**Comment by marianogabitto** [comment]
Thanks !
