### ISSUE TITLE
get raw Y  matrix

### ISSUE THREAD

**Issue by wjyzidane** [GreenleafLab/chromVAR#40]
Hi Alicia,

Thanks for developing this great tool. 

I want to check for each cell, what are the top enriched motif. So I wonder if it's possible to extract the Y matrix from chromVAR without bias corrected deviation. I think it is generated in function computeDeviations but not output to the object, right?

April

**Comment by AliciaSchep** [comment]
Can you clarify what you mean by 'top enriched motif' ? Are you looking for the rawer matrix of just how many reads are in peaks with a given motif for each cell?

**Comment by wjyzidane** [comment]
I mean the cell x motif matrix without normalization so that I can tell within a cell, which motif is more enriched than others.

**Comment by AliciaSchep** [comment]
Still not totally clear to me-- "cell x motif" tells me the dimensions but not what the values in the matrix represent.  I am still guessing you mean raw read counts, but I don't see that as being the same thing as motif enrichment.

Anyways, if aggregated read counts is what is being discussed, chromVAR does not actually compute that matrix itself as an intermediate.  It computes those values for each motif iteratively and doesn't compute the entire matrix.  However I think that should be fairly straightforward to compute from just the counts matrix and the motif matrix using matrix multiplication, something like:

```r
raw_mat <- t(assays(motif_ix)[[1]]) %*% assays(counts_filtered)[[1]]
```
