### ISSUE TITLE
error in importing single cell ATAC-seq BAM file

### ISSUE THREAD

**Issue by x811zou** [GreenleafLab/chromVAR#47]
I've been experiencing errors when I was trying to use the below command for scATAC-seq data from 10X. 
*******************************************************
fragment_counts <- getCounts("/outs/possorted_bam.bam",  peaks,  paired =  TRUE, by_rg = TRUE, format = "bam",  colData = DataFrame(celltype = "MNSC"))
----------------------------------------------
Error in serialize(data, node$con, xdr = FALSE) : 
  error writing to connection
Error: failed to stop 'SOCKcluster' cluster: error writing to connection
*******************************************************
No idea how to deal with this, does anyone has idea?
Thanks!

**Comment by AliciaSchep** [comment]
Closing this as it seems to be related to #44 -- there are two proposed solutions (one a PR -- can be tried out by installing that fork, the other a link in that thread).  Hopefully one or both of those approaches will get incorporated into chromVAR in future.
