### ISSUE TITLE
Error in counts_check(object) : ncol(object) > 1 is not TRUE

### ISSUE THREAD

**Issue by deb0612** [GreenleafLab/chromVAR#70]
When I use 
counts_filtered <- filterSamples(fragment_counts, min_depth = 1500,  min_in_peaks = 0.15, shiny = FALSE)
I got a error like 
Error in counts_check(object) : ncol(object) > 1 is not TRUE
In addition: Warning message:
In min(numeric(0), ..., na.rm = na.rm) :
  no non-missing arguments to min; returning Inf

Is there something wrong when I load my bed file?

**Comment by jsangalang** [comment]
Any answer for this??
